// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: category/options.proto

package category

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EffectKind int32

const (
	EffectKind_NETWORK  EffectKind = 0
	EffectKind_DATABASE EffectKind = 1
	EffectKind_DISK     EffectKind = 2
)

// Enum value maps for EffectKind.
var (
	EffectKind_name = map[int32]string{
		0: "NETWORK",
		1: "DATABASE",
		2: "DISK",
	}
	EffectKind_value = map[string]int32{
		"NETWORK":  0,
		"DATABASE": 1,
		"DISK":     2,
	}
)

func (x EffectKind) Enum() *EffectKind {
	p := new(EffectKind)
	*p = x
	return p
}

func (x EffectKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EffectKind) Descriptor() protoreflect.EnumDescriptor {
	return file_category_options_proto_enumTypes[0].Descriptor()
}

func (EffectKind) Type() protoreflect.EnumType {
	return &file_category_options_proto_enumTypes[0]
}

func (x EffectKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EffectKind.Descriptor instead.
func (EffectKind) EnumDescriptor() ([]byte, []int) {
	return file_category_options_proto_rawDescGZIP(), []int{0}
}

type CombineStrategy int32

const (
	CombineStrategy_INFER   CombineStrategy = 0 // Infer from field types
	CombineStrategy_CONCAT  CombineStrategy = 1 // For strings, bytes, repeated fields
	CombineStrategy_SUM     CombineStrategy = 2 // For numeric types (addition)
	CombineStrategy_PRODUCT CombineStrategy = 3 // For numeric types (multiplication)
	CombineStrategy_ALL     CombineStrategy = 4 // For bools (&&)
	CombineStrategy_ANY     CombineStrategy = 5 // For bools (||)
	CombineStrategy_FIRST   CombineStrategy = 6 // Take first non-zero value
	CombineStrategy_LAST    CombineStrategy = 7 // Take last non-zero value
	CombineStrategy_MERGE   CombineStrategy = 8 // Deep merge for nested messages
)

// Enum value maps for CombineStrategy.
var (
	CombineStrategy_name = map[int32]string{
		0: "INFER",
		1: "CONCAT",
		2: "SUM",
		3: "PRODUCT",
		4: "ALL",
		5: "ANY",
		6: "FIRST",
		7: "LAST",
		8: "MERGE",
	}
	CombineStrategy_value = map[string]int32{
		"INFER":   0,
		"CONCAT":  1,
		"SUM":     2,
		"PRODUCT": 3,
		"ALL":     4,
		"ANY":     5,
		"FIRST":   6,
		"LAST":    7,
		"MERGE":   8,
	}
)

func (x CombineStrategy) Enum() *CombineStrategy {
	p := new(CombineStrategy)
	*p = x
	return p
}

func (x CombineStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CombineStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_category_options_proto_enumTypes[1].Descriptor()
}

func (CombineStrategy) Type() protoreflect.EnumType {
	return &file_category_options_proto_enumTypes[1]
}

func (x CombineStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CombineStrategy.Descriptor instead.
func (CombineStrategy) EnumDescriptor() ([]byte, []int) {
	return file_category_options_proto_rawDescGZIP(), []int{1}
}

type CategoryFileOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Effect types to generate infrastructure for
	Effects []EffectKind `protobuf:"varint,1,rep,packed,name=effects,proto3,enum=category.EffectKind" json:"effects,omitempty"`
	// Stripe configuration (enables Stripe code generation)
	Stripe        *StripeConfig `protobuf:"bytes,10,opt,name=stripe,proto3" json:"stripe,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryFileOptions) Reset() {
	*x = CategoryFileOptions{}
	mi := &file_category_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryFileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryFileOptions) ProtoMessage() {}

func (x *CategoryFileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_category_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryFileOptions.ProtoReflect.Descriptor instead.
func (*CategoryFileOptions) Descriptor() ([]byte, []int) {
	return file_category_options_proto_rawDescGZIP(), []int{0}
}

func (x *CategoryFileOptions) GetEffects() []EffectKind {
	if x != nil {
		return x.Effects
	}
	return nil
}

func (x *CategoryFileOptions) GetStripe() *StripeConfig {
	if x != nil {
		return x.Stripe
	}
	return nil
}

// Stripe configuration
type StripeConfig struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Plans            []string               `protobuf:"bytes,1,rep,name=plans,proto3" json:"plans,omitempty"`                                                 // Plan names: ["free", "pro", "enterprise"]
	WebhookSecretEnv string                 `protobuf:"bytes,2,opt,name=webhook_secret_env,json=webhookSecretEnv,proto3" json:"webhook_secret_env,omitempty"` // Env var for webhook secret (default: STRIPE_WEBHOOK_SECRET)
	ApiKeyEnv        string                 `protobuf:"bytes,3,opt,name=api_key_env,json=apiKeyEnv,proto3" json:"api_key_env,omitempty"`                      // Env var for API key (default: STRIPE_SECRET_KEY)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *StripeConfig) Reset() {
	*x = StripeConfig{}
	mi := &file_category_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StripeConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StripeConfig) ProtoMessage() {}

func (x *StripeConfig) ProtoReflect() protoreflect.Message {
	mi := &file_category_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StripeConfig.ProtoReflect.Descriptor instead.
func (*StripeConfig) Descriptor() ([]byte, []int) {
	return file_category_options_proto_rawDescGZIP(), []int{1}
}

func (x *StripeConfig) GetPlans() []string {
	if x != nil {
		return x.Plans
	}
	return nil
}

func (x *StripeConfig) GetWebhookSecretEnv() string {
	if x != nil {
		return x.WebhookSecretEnv
	}
	return ""
}

func (x *StripeConfig) GetApiKeyEnv() string {
	if x != nil {
		return x.ApiKeyEnv
	}
	return ""
}

type CategoryMessageOptions struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Functor            bool                   `protobuf:"varint,1,opt,name=functor,proto3" json:"functor,omitempty"`                                                  // Generate Functor (FMap for slices)
	Monoid             bool                   `protobuf:"varint,2,opt,name=monoid,proto3" json:"monoid,omitempty"`                                                    // Generate Monoid (Empty + Combine)
	Semigroup          bool                   `protobuf:"varint,3,opt,name=semigroup,proto3" json:"semigroup,omitempty"`                                              // Generate Semigroup (Combine only)
	Foldable           bool                   `protobuf:"varint,4,opt,name=foldable,proto3" json:"foldable,omitempty"`                                                // Generate Fold operations
	Traversable        bool                   `protobuf:"varint,5,opt,name=traversable,proto3" json:"traversable,omitempty"`                                          // Generate Traverse for effects
	Monad              bool                   `protobuf:"varint,6,opt,name=monad,proto3" json:"monad,omitempty"`                                                      // Generate Bind for effects
	Bifunctor          bool                   `protobuf:"varint,7,opt,name=bifunctor,proto3" json:"bifunctor,omitempty"`                                              // Generate Bimap (for 2-param types)
	Combine            CombineStrategy        `protobuf:"varint,8,opt,name=combine,proto3,enum=category.CombineStrategy" json:"combine,omitempty"`                    // Override combine strategy
	FirestoreBridge    bool                   `protobuf:"varint,10,opt,name=firestore_bridge,json=firestoreBridge,proto3" json:"firestore_bridge,omitempty"`          // Generate Firestore adapters
	Global             bool                   `protobuf:"varint,11,opt,name=global,proto3" json:"global,omitempty"`                                                   // Skip tenant scoping (for cross-tenant data)
	StripeCustomer     bool                   `protobuf:"varint,20,opt,name=stripe_customer,json=stripeCustomer,proto3" json:"stripe_customer,omitempty"`             // Generate Stripe customer operations
	StripeSubscription bool                   `protobuf:"varint,21,opt,name=stripe_subscription,json=stripeSubscription,proto3" json:"stripe_subscription,omitempty"` // Generate Stripe subscription operations
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CategoryMessageOptions) Reset() {
	*x = CategoryMessageOptions{}
	mi := &file_category_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryMessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryMessageOptions) ProtoMessage() {}

func (x *CategoryMessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_category_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryMessageOptions.ProtoReflect.Descriptor instead.
func (*CategoryMessageOptions) Descriptor() ([]byte, []int) {
	return file_category_options_proto_rawDescGZIP(), []int{2}
}

func (x *CategoryMessageOptions) GetFunctor() bool {
	if x != nil {
		return x.Functor
	}
	return false
}

func (x *CategoryMessageOptions) GetMonoid() bool {
	if x != nil {
		return x.Monoid
	}
	return false
}

func (x *CategoryMessageOptions) GetSemigroup() bool {
	if x != nil {
		return x.Semigroup
	}
	return false
}

func (x *CategoryMessageOptions) GetFoldable() bool {
	if x != nil {
		return x.Foldable
	}
	return false
}

func (x *CategoryMessageOptions) GetTraversable() bool {
	if x != nil {
		return x.Traversable
	}
	return false
}

func (x *CategoryMessageOptions) GetMonad() bool {
	if x != nil {
		return x.Monad
	}
	return false
}

func (x *CategoryMessageOptions) GetBifunctor() bool {
	if x != nil {
		return x.Bifunctor
	}
	return false
}

func (x *CategoryMessageOptions) GetCombine() CombineStrategy {
	if x != nil {
		return x.Combine
	}
	return CombineStrategy_INFER
}

func (x *CategoryMessageOptions) GetFirestoreBridge() bool {
	if x != nil {
		return x.FirestoreBridge
	}
	return false
}

func (x *CategoryMessageOptions) GetGlobal() bool {
	if x != nil {
		return x.Global
	}
	return false
}

func (x *CategoryMessageOptions) GetStripeCustomer() bool {
	if x != nil {
		return x.StripeCustomer
	}
	return false
}

func (x *CategoryMessageOptions) GetStripeSubscription() bool {
	if x != nil {
		return x.StripeSubscription
	}
	return false
}

type FieldCategoryOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Combine       CombineStrategy        `protobuf:"varint,1,opt,name=combine,proto3,enum=category.CombineStrategy" json:"combine,omitempty"`
	Empty         string                 `protobuf:"bytes,2,opt,name=empty,proto3" json:"empty,omitempty"` // Custom empty value expression
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldCategoryOptions) Reset() {
	*x = FieldCategoryOptions{}
	mi := &file_category_options_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldCategoryOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldCategoryOptions) ProtoMessage() {}

func (x *FieldCategoryOptions) ProtoReflect() protoreflect.Message {
	mi := &file_category_options_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldCategoryOptions.ProtoReflect.Descriptor instead.
func (*FieldCategoryOptions) Descriptor() ([]byte, []int) {
	return file_category_options_proto_rawDescGZIP(), []int{3}
}

func (x *FieldCategoryOptions) GetCombine() CombineStrategy {
	if x != nil {
		return x.Combine
	}
	return CombineStrategy_INFER
}

func (x *FieldCategoryOptions) GetEmpty() string {
	if x != nil {
		return x.Empty
	}
	return ""
}

type CategoryServiceOptions struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Kleisli        bool                   `protobuf:"varint,1,opt,name=kleisli,proto3" json:"kleisli,omitempty"`                                     // Generate Kleisli arrow composition
	Middleware     bool                   `protobuf:"varint,2,opt,name=middleware,proto3" json:"middleware,omitempty"`                               // Generate typed middleware
	Parallel       bool                   `protobuf:"varint,3,opt,name=parallel,proto3" json:"parallel,omitempty"`                                   // Generate parallel execution helpers
	Retry          bool                   `protobuf:"varint,4,opt,name=retry,proto3" json:"retry,omitempty"`                                         // Generate retry logic
	CircuitBreaker bool                   `protobuf:"varint,5,opt,name=circuit_breaker,json=circuitBreaker,proto3" json:"circuit_breaker,omitempty"` // Generate circuit breaker
	Fanout         bool                   `protobuf:"varint,6,opt,name=fanout,proto3" json:"fanout,omitempty"`                                       // Generate fanout with monoid combine
	Mock           bool                   `protobuf:"varint,7,opt,name=mock,proto3" json:"mock,omitempty"`                                           // Generate mock implementations
	ConnectBridge  bool                   `protobuf:"varint,8,opt,name=connect_bridge,json=connectBridge,proto3" json:"connect_bridge,omitempty"`    // Generate Connect-go adapters
	StripeBilling  bool                   `protobuf:"varint,10,opt,name=stripe_billing,json=stripeBilling,proto3" json:"stripe_billing,omitempty"`   // Generate billing/plan check interceptors
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CategoryServiceOptions) Reset() {
	*x = CategoryServiceOptions{}
	mi := &file_category_options_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryServiceOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryServiceOptions) ProtoMessage() {}

func (x *CategoryServiceOptions) ProtoReflect() protoreflect.Message {
	mi := &file_category_options_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryServiceOptions.ProtoReflect.Descriptor instead.
func (*CategoryServiceOptions) Descriptor() ([]byte, []int) {
	return file_category_options_proto_rawDescGZIP(), []int{4}
}

func (x *CategoryServiceOptions) GetKleisli() bool {
	if x != nil {
		return x.Kleisli
	}
	return false
}

func (x *CategoryServiceOptions) GetMiddleware() bool {
	if x != nil {
		return x.Middleware
	}
	return false
}

func (x *CategoryServiceOptions) GetParallel() bool {
	if x != nil {
		return x.Parallel
	}
	return false
}

func (x *CategoryServiceOptions) GetRetry() bool {
	if x != nil {
		return x.Retry
	}
	return false
}

func (x *CategoryServiceOptions) GetCircuitBreaker() bool {
	if x != nil {
		return x.CircuitBreaker
	}
	return false
}

func (x *CategoryServiceOptions) GetFanout() bool {
	if x != nil {
		return x.Fanout
	}
	return false
}

func (x *CategoryServiceOptions) GetMock() bool {
	if x != nil {
		return x.Mock
	}
	return false
}

func (x *CategoryServiceOptions) GetConnectBridge() bool {
	if x != nil {
		return x.ConnectBridge
	}
	return false
}

func (x *CategoryServiceOptions) GetStripeBilling() bool {
	if x != nil {
		return x.StripeBilling
	}
	return false
}

type CategoryMethodOptions struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Idempotent bool                   `protobuf:"varint,1,opt,name=idempotent,proto3" json:"idempotent,omitempty"`            // Safe to retry
	Fallback   string                 `protobuf:"bytes,2,opt,name=fallback,proto3" json:"fallback,omitempty"`                 // Fallback method name
	CacheKey   string                 `protobuf:"bytes,3,opt,name=cache_key,json=cacheKey,proto3" json:"cache_key,omitempty"` // Cache key expression for memoization
	// Stripe billing options
	MinPlan       string `protobuf:"bytes,10,opt,name=min_plan,json=minPlan,proto3" json:"min_plan,omitempty"`          // Minimum plan required (e.g., "pro", "enterprise")
	Metered       bool   `protobuf:"varint,11,opt,name=metered,proto3" json:"metered,omitempty"`                        // Track usage for this method
	MeterEvent    string `protobuf:"bytes,12,opt,name=meter_event,json=meterEvent,proto3" json:"meter_event,omitempty"` // Usage event name (default: method name)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CategoryMethodOptions) Reset() {
	*x = CategoryMethodOptions{}
	mi := &file_category_options_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CategoryMethodOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CategoryMethodOptions) ProtoMessage() {}

func (x *CategoryMethodOptions) ProtoReflect() protoreflect.Message {
	mi := &file_category_options_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CategoryMethodOptions.ProtoReflect.Descriptor instead.
func (*CategoryMethodOptions) Descriptor() ([]byte, []int) {
	return file_category_options_proto_rawDescGZIP(), []int{5}
}

func (x *CategoryMethodOptions) GetIdempotent() bool {
	if x != nil {
		return x.Idempotent
	}
	return false
}

func (x *CategoryMethodOptions) GetFallback() string {
	if x != nil {
		return x.Fallback
	}
	return ""
}

func (x *CategoryMethodOptions) GetCacheKey() string {
	if x != nil {
		return x.CacheKey
	}
	return ""
}

func (x *CategoryMethodOptions) GetMinPlan() string {
	if x != nil {
		return x.MinPlan
	}
	return ""
}

func (x *CategoryMethodOptions) GetMetered() bool {
	if x != nil {
		return x.Metered
	}
	return false
}

func (x *CategoryMethodOptions) GetMeterEvent() string {
	if x != nil {
		return x.MeterEvent
	}
	return ""
}

var file_category_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*CategoryFileOptions)(nil),
		Field:         50000,
		Name:          "category.category_file",
		Tag:           "bytes,50000,opt,name=category_file",
		Filename:      "category/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*CategoryMessageOptions)(nil),
		Field:         50001,
		Name:          "category.category",
		Tag:           "bytes,50001,opt,name=category",
		Filename:      "category/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldCategoryOptions)(nil),
		Field:         50002,
		Name:          "category.field_category",
		Tag:           "bytes,50002,opt,name=field_category",
		Filename:      "category/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*CategoryServiceOptions)(nil),
		Field:         50003,
		Name:          "category.category_service",
		Tag:           "bytes,50003,opt,name=category_service",
		Filename:      "category/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*CategoryMethodOptions)(nil),
		Field:         50004,
		Name:          "category.category_method",
		Tag:           "bytes,50004,opt,name=category_method",
		Filename:      "category/options.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// optional category.CategoryFileOptions category_file = 50000;
	E_CategoryFile = &file_category_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional category.CategoryMessageOptions category = 50001;
	E_Category = &file_category_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional category.FieldCategoryOptions field_category = 50002;
	E_FieldCategory = &file_category_options_proto_extTypes[2]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional category.CategoryServiceOptions category_service = 50003;
	E_CategoryService = &file_category_options_proto_extTypes[3]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional category.CategoryMethodOptions category_method = 50004;
	E_CategoryMethod = &file_category_options_proto_extTypes[4]
)

var File_category_options_proto protoreflect.FileDescriptor

const file_category_options_proto_rawDesc = "" +
	"\n" +
	"\x16category/options.proto\x12\bcategory\x1a google/protobuf/descriptor.proto\"u\n" +
	"\x13CategoryFileOptions\x12.\n" +
	"\aeffects\x18\x01 \x03(\x0e2\x14.category.EffectKindR\aeffects\x12.\n" +
	"\x06stripe\x18\n" +
	" \x01(\v2\x16.category.StripeConfigR\x06stripe\"r\n" +
	"\fStripeConfig\x12\x14\n" +
	"\x05plans\x18\x01 \x03(\tR\x05plans\x12,\n" +
	"\x12webhook_secret_env\x18\x02 \x01(\tR\x10webhookSecretEnv\x12\x1e\n" +
	"\vapi_key_env\x18\x03 \x01(\tR\tapiKeyEnv\"\xac\x03\n" +
	"\x16CategoryMessageOptions\x12\x18\n" +
	"\afunctor\x18\x01 \x01(\bR\afunctor\x12\x16\n" +
	"\x06monoid\x18\x02 \x01(\bR\x06monoid\x12\x1c\n" +
	"\tsemigroup\x18\x03 \x01(\bR\tsemigroup\x12\x1a\n" +
	"\bfoldable\x18\x04 \x01(\bR\bfoldable\x12 \n" +
	"\vtraversable\x18\x05 \x01(\bR\vtraversable\x12\x14\n" +
	"\x05monad\x18\x06 \x01(\bR\x05monad\x12\x1c\n" +
	"\tbifunctor\x18\a \x01(\bR\tbifunctor\x123\n" +
	"\acombine\x18\b \x01(\x0e2\x19.category.CombineStrategyR\acombine\x12)\n" +
	"\x10firestore_bridge\x18\n" +
	" \x01(\bR\x0ffirestoreBridge\x12\x16\n" +
	"\x06global\x18\v \x01(\bR\x06global\x12'\n" +
	"\x0fstripe_customer\x18\x14 \x01(\bR\x0estripeCustomer\x12/\n" +
	"\x13stripe_subscription\x18\x15 \x01(\bR\x12stripeSubscription\"a\n" +
	"\x14FieldCategoryOptions\x123\n" +
	"\acombine\x18\x01 \x01(\x0e2\x19.category.CombineStrategyR\acombine\x12\x14\n" +
	"\x05empty\x18\x02 \x01(\tR\x05empty\"\xa7\x02\n" +
	"\x16CategoryServiceOptions\x12\x18\n" +
	"\akleisli\x18\x01 \x01(\bR\akleisli\x12\x1e\n" +
	"\n" +
	"middleware\x18\x02 \x01(\bR\n" +
	"middleware\x12\x1a\n" +
	"\bparallel\x18\x03 \x01(\bR\bparallel\x12\x14\n" +
	"\x05retry\x18\x04 \x01(\bR\x05retry\x12'\n" +
	"\x0fcircuit_breaker\x18\x05 \x01(\bR\x0ecircuitBreaker\x12\x16\n" +
	"\x06fanout\x18\x06 \x01(\bR\x06fanout\x12\x12\n" +
	"\x04mock\x18\a \x01(\bR\x04mock\x12%\n" +
	"\x0econnect_bridge\x18\b \x01(\bR\rconnectBridge\x12%\n" +
	"\x0estripe_billing\x18\n" +
	" \x01(\bR\rstripeBilling\"\xc6\x01\n" +
	"\x15CategoryMethodOptions\x12\x1e\n" +
	"\n" +
	"idempotent\x18\x01 \x01(\bR\n" +
	"idempotent\x12\x1a\n" +
	"\bfallback\x18\x02 \x01(\tR\bfallback\x12\x1b\n" +
	"\tcache_key\x18\x03 \x01(\tR\bcacheKey\x12\x19\n" +
	"\bmin_plan\x18\n" +
	" \x01(\tR\aminPlan\x12\x18\n" +
	"\ametered\x18\v \x01(\bR\ametered\x12\x1f\n" +
	"\vmeter_event\x18\f \x01(\tR\n" +
	"meterEvent*1\n" +
	"\n" +
	"EffectKind\x12\v\n" +
	"\aNETWORK\x10\x00\x12\f\n" +
	"\bDATABASE\x10\x01\x12\b\n" +
	"\x04DISK\x10\x02*p\n" +
	"\x0fCombineStrategy\x12\t\n" +
	"\x05INFER\x10\x00\x12\n" +
	"\n" +
	"\x06CONCAT\x10\x01\x12\a\n" +
	"\x03SUM\x10\x02\x12\v\n" +
	"\aPRODUCT\x10\x03\x12\a\n" +
	"\x03ALL\x10\x04\x12\a\n" +
	"\x03ANY\x10\x05\x12\t\n" +
	"\x05FIRST\x10\x06\x12\b\n" +
	"\x04LAST\x10\a\x12\t\n" +
	"\x05MERGE\x10\b:b\n" +
	"\rcategory_file\x12\x1c.google.protobuf.FileOptions\x18І\x03 \x01(\v2\x1d.category.CategoryFileOptionsR\fcategoryFile:_\n" +
	"\bcategory\x12\x1f.google.protobuf.MessageOptions\x18ц\x03 \x01(\v2 .category.CategoryMessageOptionsR\bcategory:f\n" +
	"\x0efield_category\x12\x1d.google.protobuf.FieldOptions\x18҆\x03 \x01(\v2\x1e.category.FieldCategoryOptionsR\rfieldCategory:n\n" +
	"\x10category_service\x12\x1f.google.protobuf.ServiceOptions\x18ӆ\x03 \x01(\v2 .category.CategoryServiceOptionsR\x0fcategoryService:j\n" +
	"\x0fcategory_method\x12\x1e.google.protobuf.MethodOptions\x18Ԇ\x03 \x01(\v2\x1f.category.CategoryMethodOptionsR\x0ecategoryMethodB@Z>github.com/example/protoc-gen-category/proto/category;categoryb\x06proto3"

var (
	file_category_options_proto_rawDescOnce sync.Once
	file_category_options_proto_rawDescData []byte
)

func file_category_options_proto_rawDescGZIP() []byte {
	file_category_options_proto_rawDescOnce.Do(func() {
		file_category_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_category_options_proto_rawDesc), len(file_category_options_proto_rawDesc)))
	})
	return file_category_options_proto_rawDescData
}

var file_category_options_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_category_options_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_category_options_proto_goTypes = []any{
	(EffectKind)(0),                     // 0: category.EffectKind
	(CombineStrategy)(0),                // 1: category.CombineStrategy
	(*CategoryFileOptions)(nil),         // 2: category.CategoryFileOptions
	(*StripeConfig)(nil),                // 3: category.StripeConfig
	(*CategoryMessageOptions)(nil),      // 4: category.CategoryMessageOptions
	(*FieldCategoryOptions)(nil),        // 5: category.FieldCategoryOptions
	(*CategoryServiceOptions)(nil),      // 6: category.CategoryServiceOptions
	(*CategoryMethodOptions)(nil),       // 7: category.CategoryMethodOptions
	(*descriptorpb.FileOptions)(nil),    // 8: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 9: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 10: google.protobuf.FieldOptions
	(*descriptorpb.ServiceOptions)(nil), // 11: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 12: google.protobuf.MethodOptions
}
var file_category_options_proto_depIdxs = []int32{
	0,  // 0: category.CategoryFileOptions.effects:type_name -> category.EffectKind
	3,  // 1: category.CategoryFileOptions.stripe:type_name -> category.StripeConfig
	1,  // 2: category.CategoryMessageOptions.combine:type_name -> category.CombineStrategy
	1,  // 3: category.FieldCategoryOptions.combine:type_name -> category.CombineStrategy
	8,  // 4: category.category_file:extendee -> google.protobuf.FileOptions
	9,  // 5: category.category:extendee -> google.protobuf.MessageOptions
	10, // 6: category.field_category:extendee -> google.protobuf.FieldOptions
	11, // 7: category.category_service:extendee -> google.protobuf.ServiceOptions
	12, // 8: category.category_method:extendee -> google.protobuf.MethodOptions
	2,  // 9: category.category_file:type_name -> category.CategoryFileOptions
	4,  // 10: category.category:type_name -> category.CategoryMessageOptions
	5,  // 11: category.field_category:type_name -> category.FieldCategoryOptions
	6,  // 12: category.category_service:type_name -> category.CategoryServiceOptions
	7,  // 13: category.category_method:type_name -> category.CategoryMethodOptions
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	9,  // [9:14] is the sub-list for extension type_name
	4,  // [4:9] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_category_options_proto_init() }
func file_category_options_proto_init() {
	if File_category_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_category_options_proto_rawDesc), len(file_category_options_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 5,
			NumServices:   0,
		},
		GoTypes:           file_category_options_proto_goTypes,
		DependencyIndexes: file_category_options_proto_depIdxs,
		EnumInfos:         file_category_options_proto_enumTypes,
		MessageInfos:      file_category_options_proto_msgTypes,
		ExtensionInfos:    file_category_options_proto_extTypes,
	}.Build()
	File_category_options_proto = out.File
	file_category_options_proto_goTypes = nil
	file_category_options_proto_depIdxs = nil
}
